#!/usr/bin/env node
/**
 * @file Writes the theme reference page.
 *
 * The table is the theme table — a page listing 79 themes by hand would be wrong within a release.
 * Run it after touching `packages/core/src/themes/index.ts`; `--check` is what CI runs.
 *
 * The output goes through oxfmt, as the GraphQL generator's does, so `pnpm format` leaves it alone
 * and `--check` compares against what the formatter would have written anyway.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

import { oxfmtConfig } from '@marcalexiei/oxfmt-config';
import { themes } from '@stats-forge/github-stats-forge-core/themes';
import { format } from 'oxfmt';

import { SAMPLE_THEMES, THEMES_DIR } from '../src/constants.ts';

const PAGE = fileURLToPath(
  new URL('../src/content/docs/docs/customization/themes.md', import.meta.url),
);

/** The four colors every theme names, in the order the table shows them. */
const CHANNELS = ['title_color', 'icon_color', 'text_color', 'bg_color'] as const;

/**
 * A swatch and the value behind it, as one cell.
 * `bg_color` can hold a gradient — an angle in degrees, then its stops — which draws as one too,
 * so no cell is a bare string of numbers with nothing to look at.
 *
 * @returns The cell's markdown.
 */
const swatch = (value: string): string => {
  const [angle, ...stops] = value.split(',');
  const background =
    stops.length > 0
      ? `linear-gradient(${angle ?? '0'}deg, ${stops.map((stop) => `#${stop}`).join(', ')})`
      : `#${value}`;
  const wide = stops.length > 0 ? ' theme-swatch--wide' : '';

  return `<span class="theme-swatch${wide}" style="background:${background}"></span> \`${value}\``;
};

/**
 * @returns The whole page.
 */
const render = (): string => {
  const rows = Object.entries(themes).map(
    ([name, theme]) =>
      `| \`${name}\` | ${CHANNELS.map((channel) => swatch(theme[channel])).join(' | ')} |`,
  );

  return [
    '---',
    'title: Themes',
    `description: The ${String(rows.length)} built-in themes, and the colors each one sets.`,
    '---',
    '',
    '<!-- Generated by scripts/generate-themes-page.ts. Edit the theme table in packages/core instead. -->',
    '',
    'Pass one by name:',
    '',
    '```text',
    '?username=octocat&theme=tokyonight',
    '```',
    '',
    'An unknown name is not an error — it falls back to `default`, so a typo still renders a card.',
    'Any color you pass alongside a theme wins over the theme, so `theme` is a starting point',
    'rather than a lock: see [Common options](../common-options/) for the color params.',
    '',
    '## A few of them, drawn',
    '',
    'The same stats card, rendered by the CLI in six of the themes below.',
    '',
    ...SAMPLE_THEMES.flatMap((name) => [
      `### \`${name}\``,
      '',
      `![The stats card in the ${name} theme](/${THEMES_DIR}/${name}.svg)`,
      '',
    ]),
    `## The ${String(rows.length)} built-in themes`,
    '',
    '| Theme | Title | Icon | Text | Background |',
    '| ----- | ----- | ---- | ---- | ---------- |',
    ...rows,
    '',
  ].join('\n');
};

const { values } = parseArgs({ options: { check: { type: 'boolean', default: false } } });
const formatted = await format(PAGE, render(), oxfmtConfig);
const page = formatted.code;

if (values.check) {
  const current = await readFile(PAGE, 'utf8').catch(() => '');
  if (current !== page) {
    process.stderr.write(
      'themes.md is out of date. Run `pnpm --filter ./apps/docs run generate-themes-page`.\n',
    );
    process.exitCode = 1;
  }
} else {
  await writeFile(PAGE, page, 'utf8');
  process.stdout.write(`Wrote ${PAGE}\n`);
}
