name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  build-and-test:
    name: Build and test ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [24, 26]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: marcalexiei/github-actions/setup-node-and-pnpm@d5a5561c7caea4f18642f3967aad095af51c3905 # v2.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Build packages
        run: pnpm run build:packages

      - name: Run tests
        run: pnpm run test

  code-checks:
    name: Code checks

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: marcalexiei/github-actions/setup-node-and-pnpm@d5a5561c7caea4f18642f3967aad095af51c3905 # v2.1.0

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Lint (knip)
        run: pnpm run lint:knip

      - name: Lint (deduped deps)
        run: pnpm run lint:deps

      - name: Lint (generated GraphQL types)
        run: pnpm --filter ./packages/core/ run check-graphql-types

      - name: Typecheck
        run: pnpm run typecheck

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build-and-test
      - code-checks
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
