name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  build-and-test:
    name: Build and test ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [24]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: Build packages
        run: pnpm run build:packages

      - name: Run tests
        run: pnpm run test

  code-checks:
    name: Code checks

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Lint (knip)
        run: pnpm run lint:knip

      - name: Lint (deduped deps)
        run: pnpm run lint:deps

      - name: Lint (generated GraphQL types)
        run: pnpm --filter ./packages/core/ run check-graphql-types

      - name: Typecheck
        run: pnpm run typecheck
